name: group_button
description: Flutter custom widget to make a group buttons. Included Radio and CheckBox buttons.
version: 4.2.0
homepage: https://github.com/Frezyx/group_button

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
